package com.dhivi.inc.topo.plugin;

import com.dhivi.inc.topo.plugin.holder.AppResponseData;

import retrofit2.Call;
import retrofit2.http.Field;
import retrofit2.http.FormUrlEncoded;
import retrofit2.http.GET;
import retrofit2.http.POST;
import retrofit2.http.Query;

/**
 * Created by Manoj on 9/22/2017.
 */

public interface APIInterface {

    @FormUrlEncoded
    @POST("/app/signup_check.php")
    Call<AppResponseData> doSignUpCheck(@Field("source") String source, @Field("email") String email);

    @FormUrlEncoded
    @POST("/app/signin.php")
    Call<AppResponseData> doSignin(@Field("source") String source,@Field("token") String token, @Field("topo_user_email") String topo_user_email, @Field("topo_password_password") String topo_password_password,@Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/signup.php")
    Call<AppResponseData> doSignUp(@Field("source") String source,@Field("token") String token, @Field("topo_user_name") String topo_user_name,@Field("topo_user_email") String topo_user_email, @Field("topo_user_mobile") String topo_user_mobile, @Field("topo_user_referred_by") String topo_user_referred_by,@Field("topo_image_url") String topo_image_url,@Field("topo_user_country") String topo_user_country,@Field("topo_password_password") String topo_password_password,@Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/password_reset_request.php")
    Call<AppResponseData> doReset(@Field("source") String source, @Field("topo_user_email") String topo_user_email, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/change_password.php")
    Call<AppResponseData> doChangePassword(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("old_password") String old_password,@Field("topo_password_password") String topo_password_password, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/home.php")
    Call<AppResponseData> doHome(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/fetch_contacts.php")
    Call<AppResponseData> dofetchContacts(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/saved_topos_list.php")
    Call<AppResponseData> doSavedTopos(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/search_default.php")
    Call<AppResponseData> doSearchTopos(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/search.php")
    Call<AppResponseData> doSearchResultTopos(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("search_word") String search_word, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/request_delete.php")
    Call<AppResponseData> doRequestDelete(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("topo_request_id") String topo_request_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/request_topo.php")
    Call<AppResponseData> doRequestTopo(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("to_topo_user_id") String to_topo_user_id, @Field("topo_request_message") String topo_request_message,  @Field("topo_id") String topo_id,@Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/request_view.php")
    Call<AppResponseData> doRequestView(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("topo_request_id") String topo_request_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/save_topo.php")
    Call<AppResponseData> doSaveTopo(@Field("topo_business_name") String topo_business_name,@Field("topo_is_business") String topo_is_business,@Field("topo_business_category") String topo_business_category,@Field("topo_working_days") String topo_working_days,@Field("topo_working_hours_from") String topo_working_hours_from,@Field("topo_working_hours_to") String topo_working_hours_to,@Field("topo_contact_number") String topo_contact_number,@Field("source") String source,@Field("topo_flat_no") String topo_flat_no,@Field("topo_pincode") String topo_pincode,@Field("topo_city") String topo_city,@Field("topo_country") String topo_country,@Field("topo_address") String topo_address,@Field("topo_lon") String topo_lon,@Field("topo_lat") String topo_lat,@Field("topo_name") String topo_name,@Field("topo_privacy") String topo_privacy, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/send_topo.php")
    Call<AppResponseData> doSendTopo(@Field("source") String source,@Field("topo_id") String topo_id,@Field("to_topo_user_id") String to_topo_user_id, @Field("topo_user_id") String topo_user_id,@Field("time_period") String time_period, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/send_from_request.php")
    Call<AppResponseData> doSendTopoRequest(@Field("source") String source,@Field("topo_request_id") String topo_request_id,@Field("topo_id") String topo_id,@Field("to_topo_user_id") String to_topo_user_id, @Field("topo_user_id") String topo_user_id,@Field("time_period") String time_period, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/topo_availability.php")
    Call<AppResponseData> doTopoAvailability(@Field("source") String source,@Field("topo_name") String topo_name, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    /*@FormUrlEncoded
    @POST("/app/update_topo.php")
    Call<AppResponseData> doUpdateTopo(@Field("source") String source,@Field("topo_flat_no") String topo_flat_no,@Field("topo_pincode") String topo_pincode,@Field("topo_city") String topo_city,@Field("topo_country") String topo_country,@Field("topo_address") String topo_address,@Field("topo_lon") String topo_lon,@Field("topo_lat") String topo_lat,@Field("topo_name") String topo_name,@Field("topo_privacy") String topo_privacy, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);
*/
    @FormUrlEncoded
    @POST("/app/update_topo.php")
    Call<AppResponseData> doUpdateTopo(@Field("topo_business_name") String topo_business_name,@Field("topo_is_business") String topo_is_business,@Field("topo_business_category") String topo_business_category,@Field("topo_working_days") String topo_working_days,@Field("topo_working_hours_from") String topo_working_hours_from,@Field("topo_working_hours_to") String topo_working_hours_to,@Field("topo_contact_number") String topo_contact_number,@Field("source") String source,@Field("topo_flat_no") String topo_flat_no,@Field("topo_pincode") String topo_pincode,@Field("topo_city") String topo_city,@Field("topo_country") String topo_country,@Field("topo_address") String topo_address,@Field("topo_lon") String topo_lon,@Field("topo_lat") String topo_lat,@Field("topo_name") String topo_name,@Field("topo_privacy") String topo_privacy, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);


    @FormUrlEncoded
    @POST("/app/topo_stats_create.php")
    Call<AppResponseData> doTopoStats(@Field("source") String source, @Field("topo_stat_item") String topo_stat_item, @Field("topo_stat_action") String topo_stat_action, @Field("topo_name") String topo_name, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/topo_view.php")
    Call<AppResponseData> doTopoView(@Field("source") String source,@Field("topo_user_id") String topo_user_id, @Field("topo_name") String topo_name, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/topo_delete.php")
    Call<AppResponseData> doTopoDelete(@Field("source") String source, @Field("topo_name") String topo_name, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/add_to_topos.php")
    Call<AppResponseData> doAddToTopos(@Field("source") String source, @Field("topo_name") String topo_name, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/start_navigation.php")
    Call<AppResponseData> doStratNavigation(@Field("source") String source, @Field("topo_name") String topo_name, @Field("topo_user_id") String topo_user_id,@Field("to_topo_user_id") String to_topo_user_id,@Field("topo_id") String topo_id,@Field("topo_lat") String topo_lat,@Field("topo_long") String topo_long, @Field("topo_type") String topo_type, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/stop_navigation.php")
    Call<AppResponseData> dostopnavigation(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("topo_navigation_id") String topo_navigation_id,@Field("topo_id") String topo_id,@Field("topo_lat") String topo_lat,@Field("topo_long") String topo_long,@Field("topo_type") String topo_type, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/delete_from_list.php")
    Call<AppResponseData> doDeleteFromTopos(@Field("source") String source, @Field("topo_name") String topo_name, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/instant_topo_save.php")
    Call<AppResponseData> doInstantSaveTopo(@Field("source") String source,@Field("topo_flat_no") String topo_flat_no,@Field("topo_pincode") String topo_pincode,@Field("topo_city") String topo_city,@Field("topo_country") String topo_country,@Field("topo_address") String topo_address,@Field("topo_lon") String topo_lon,@Field("topo_lat") String topo_lat, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/instant_topo_send.php")
    Call<AppResponseData> doInstantTopoSend(@Field("source") String source, @Field("topo_instant_id") String topo_instant_id, @Field("to_topo_user_id") String to_topo_user_id, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/instant_topo_view.php")
    Call<AppResponseData> doInstantTopoView(@Field("source") String source, @Field("topo_instant_id") String topo_instant_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/instant_topo_delete.php")
    Call<AppResponseData> doInstantTopoDelete(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("topo_instant_id") String topo_instant_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/help.php")
    Call<AppResponseData> doHelp(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("topo_help_message") String topo_help_message, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/feedback.php")
    Call<AppResponseData> doFeedback(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("topo_feedback_message") String topo_feedback_message,@Field("topo_feedback_rating") String topo_feedback_rating, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/logout.php")
    Call<AppResponseData> doLogout(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/profile_update.php")
    Call<AppResponseData> doProfileUpdate(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("topo_user_mobile") String topo_user_mobile, @Field("topo_user_email") String topo_user_email, @Field("topo_user_gender") String topo_user_gender, @Field("topo_image_url") String topo_image_url, @Field("topo_user_name") String topo_user_name, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/remove_profile_photo.php")
    Call<AppResponseData> doRemoveImage(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/feedback_list.php")
    Call<AppResponseData> doFeedbackList(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/profile_view.php")
    Call<AppResponseData> doProfileView(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/update_navigation.php")
    Call<AppResponseData> doupdatenavigation(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("topo_navigation_id") String topo_navigation_id,@Field("topo_id") String topo_id,@Field("topo_lat") String topo_lat,@Field("topo_long") String topo_long,@Field("topo_type") String topo_type, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/live_navigation.php")
    Call<AppResponseData> doLiveTrackView(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("topo_id") String topo_id,@Field("topo_type") String topo_type, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/access_list.php")
    Call<AppResponseData> doAccessList(@Field("source") String source,@Field("topo_name") String topo_name, @Field("topo_user_id") String topo_user_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/access_update.php")
    Call<AppResponseData> doAccessUpdate(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("topo_access_id") String topo_access_id,@Field("topo_access_period") String topo_access_period, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/access_delete.php")
    Call<AppResponseData> doAccessDelete(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("topo_access_id") String topo_access_id, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/contactsExport.php")
    Call<AppResponseData> doSendingContacts(@Field("source") String source, @Field("topo_user_id") String topo_user_id,@Field("contacts_file_path") String contacts_file_path, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/fb_oauth.php")
    Call<AppResponseData> doFbOauth(@Field("source") String source,@Field("token") String token, @Field("topo_user_mobile") String topo_user_mobile, @Field("country_code") String country_code,@Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/update_user_name.php")
    Call<AppResponseData> doUserNameUpdate(@Field("source") String source, @Field("topo_user_id") String topo_user_id, @Field("topo_user_name") String topo_user_name, @Field("imei_1") String imei_1,@Field("imei_2") String imei_2, @Field("tracking_device") String tracking_device, @Field("tracking_os") String tracking_os, @Field("tracking_model") String tracking_model, @Field("tracking_browser_name") String tracking_browser_name, @Field("tracking_browser_version") String tracking_browser_version, @Field("tracking_is_app") String tracking_is_app, @Field("tracking_app_version") String tracking_app_version, @Field("tracking_lat") String tracking_lat, @Field("tracking_lan") String tracking_lan, @Field("tracking_login_key") String tracking_login_key, @Field("tracking_ip") String tracking_ip, @Field("tracking_on") String tracking_on, @Field("tracking_action") String tracking_action);

    @FormUrlEncoded
    @POST("/app/countries_list.php")
    Call<AppResponseData> doUserCountriesList(@Field("source") String source);
    // counriesList is object and calling_code is number

    @GET("sendotp.php?authkey=187693AxlPgz3KL8Uv5a2ec6aa&mobile=&message=&sender=TOPOID")
    Call<AppResponseData>doSendOtp(@Query("mobile")String mobile,@Query("message")String message,@Query("otp")String otp);

    @GET("retryotp.php?authkey=187693AxlPgz3KL8Uv5a2ec6aa&mobile=")
    Call<AppResponseData>doResendOtp(@Query("mobile")String mobile);

}
